project_id = "aneqcnlhxsvfyevetmua"
[functions.whatsapp-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-proxy/*.html" ]

[functions.user-signup-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/user-signup-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-signup-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/user-signup-webhook/*.html" ]

[functions.cron-daily-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/cron-daily-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cron-daily-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cron-daily-reminders/*.html" ]
